on:
  push:
    branches:
    - main
    paths:
    - 'README.Rmd'
name: Check README renders
jobs:
  knit-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install Missing Packages
      run: |
        install.packages("remotes")
        remotes::install_github("rundel/checklist")
        checklist::install_missing_pkgs(dir = "./", glob = "README.Rmd")
      shell: Rscript {0}
    - name: Check Renders
      run: |
        checklist::check_rmd_renders("README.Rmd")
      shell: Rscript {0}
